In [133]:
import pandas as pd

In [134]:
df = pd.read_csv('austin_weather.csv')

In [135]:
df.shape

(1319, 21)

In [136]:
df.isnull().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64

In [137]:
df = df.drop_duplicates()

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   object
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      1319 non-null   object
dtypes: int64(3), object(18)
memory usage: 216.5+ KB

In [139]:
df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,21-12-13,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,22-12-13,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,23-12-13,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,24-12-13,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,25-12-13,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,

In [140]:
df = df[~df.eq("-").any(axis=1)]

In [141]:
df.shape

(1305, 21)

In [142]:
import numpy as np

df['DewPointHighF'] = pd.to_numeric(df['DewPointHighF'])
df['DewPointAvgF'] = pd.to_numeric(df['DewPointAvgF'])
df['DewPointLowF'] = pd.to_numeric(df['DewPointLowF'])
df['HumidityHighPercent'] = pd.to_numeric(df['HumidityHighPercent'])
df['HumidityAvgPercent'] = pd.to_numeric(df['HumidityAvgPercent'])
df['HumidityLowPercent'] = pd.to_numeric(df['HumidityLowPercent'])
df['SeaLevelPressureHighInches'] = df['DewPointLowF'].astype(float)
df['SeaLevelPressureAvgInches'] = df['SeaLevelPressureAvgInches'].astype(float)
df['SeaLevelPressureLowInches'] = df['SeaLevelPressureLowInches'].astype(float)
df['SeaLevelPressureLowInches'] = df['SeaLevelPressureLowInches'].astype(float)
df['VisibilityAvgMiles'] = pd.to_numeric(df['VisibilityAvgMiles'])
df['VisibilityLowMiles'] = pd.to_numeric(df['VisibilityLowMiles'])
df['VisibilityHighMiles'] = pd.to_numeric(df['VisibilityHighMiles'])
df['WindHighMPH'] = pd.to_numeric(df['WindHighMPH'])
df['WindAvgMPH'] = pd.to_numeric(df['WindAvgMPH'])
df['WindGustMPH'] = pd.to_numeric(df['WindGustMPH'])
df['WindAvgMPH'] = pd.to_numeric(df['WindAvgMPH'])

df['PrecipitationSumInches'] = pd.to_numeric(df['PrecipitationSumInches'].replace('T',np.nan))

df['PrecipitationSumInches'] = df['PrecipitationSumInches'].fillna(df['PrecipitationSumInches'].mean())

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1305 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1305 non-null   object
 1   TempHighF                   1305 non-null   int64
 2   TempAvgF                    1305 non-null   int64
 3   TempLowF                    1305 non-null   int64
 4   DewPointHighF               1305 non-null   int64
 5   DewPointAvgF                1305 non-null   int64
 6   DewPointLowF                1305 non-null   int64
 7   HumidityHighPercent         1305 non-null   int64
 8   HumidityAvgPercent          1305 non-null   int64
 9   HumidityLowPercent          1305 non-null   int64
 10  SeaLevelPressureHighInches  1305 non-null   float64
 11  SeaLevelPressureAvgInches   1305 non-null   float64
 12  SeaLevelPressureLowInches   1305 non-null   float64
 13  VisibilityHighMiles         1305 non-null   int64
 14  VisibilityAvgMiles          1305 non-null   int64
 15  VisibilityLowMiles          1305 non-null   int64
 16  WindHighMPH                 1305 non-null   int64
 17  WindAvgMPH                  1305 non-null   int64
 18  WindGustMPH                 1305 non-null   int64
 19  PrecipitationSumInches      1305 non-null   float64
 20  Events                      1305 non-null   object
dtypes: float64(4), int64(15), object(2)
memory usage: 224.3+ KB

In [144]:
df.isnull().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64

In [145]:
df['Events'] = df['Events'].fillna("").str.contains(r"\bRain\b",case=False, na=False).astype(int)

In [146]:
df.describe()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
count,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000,1305.000000
mean,80.792337,70.557854,59.819923,61.516475,56.636782,50.944061,87.833716,66.662835,44.983908,50.944061,30.022835,29.931609,9.991571,9.162452,6.842912,13.245211,5.009195,21.383908,0.127380,0.287356
std,14.710570,14.009579,14.193089,13.578896,14.862556,16.187999,11.049003,12.503302,17.013137,16.187999,0.171879,0.171921,0.163614,1.459463,3.680365,3.425537,2.081891,5.887797,0.428706,0.452703
min,32.000000,29.000000,19.000000,13.000000,8.000000,2.000000,37.000000,27.000000,10.000000,2.000000,29.550000,29.410000,5.000000,2.000000,0.000000,6.000000,1.000000,9.000000,0.000000,0.000000
25%,72.000000,62.000000,49.000000,53.000000,46.000000,38.000000,85.000000,59.000000,33.000000,38.000000,29.910000,29.820000,10.000000,9.000000,3.000000,10.000000,3.000000,17.000000,0.000000,0.000000
50%,83.000000,73.000000,62.000000,66.000000,61.000000,56.000000,90.000000,67.000000,44.000000,56.000000,30.000000,29.910000,10.000000,10.000000,9.000000,13.000000,5.000000,21.000000,0.000000,0.000000
75%,92.000000,83.000000,73.000000,73.000000,69.000000,65.000000,94.000000,74.000000,55.000000,65.000000,30.100000,30.020000,10.000000,10.000000,10.000000,15.000000,6.000000,25.000000,0.080000,1.000000
max,107.000000,93.000000,81.000000,80.000000,76.000000,75.000000,100.000000,97.000000,93.000000,75.000000,30.740000,30.610000,10.000000,10.000000,10.000000,29.000000,12.000000,57.000000,5.200000,1.000000

In [147]:
df['Events'].unique()

array([1, 0])

In [148]:
df['Events'].value_counts()

Events
0    930
1    375
Name: count, dtype: int64

In [149]:
df.isnull().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1305 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1305 non-null   object
 1   TempHighF                   1305 non-null   int64
 2   TempAvgF                    1305 non-null   int64
 3   TempLowF                    1305 non-null   int64
 4   DewPointHighF               1305 non-null   int64
 5   DewPointAvgF                1305 non-null   int64
 6   DewPointLowF                1305 non-null   int64
 7   HumidityHighPercent         1305 non-null   int64
 8   HumidityAvgPercent          1305 non-null   int64
 9   HumidityLowPercent          1305 non-null   int64
 10  SeaLevelPressureHighInches  1305 non-null   float64
 11  SeaLevelPressureAvgInches   1305 non-null   float64
 12  SeaLevelPressureLowInches   1305 non-null   float64
 13  VisibilityHighMiles         1305 non-null   int64
 14  VisibilityAvgMiles          1305 non-null   int64
 15  VisibilityLowMiles          1305 non-null   int64
 16  WindHighMPH                 1305 non-null   int64
 17  WindAvgMPH                  1305 non-null   int64
 18  WindGustMPH                 1305 non-null   int64
 19  PrecipitationSumInches      1305 non-null   float64
 20  Events                      1305 non-null   int64
dtypes: float64(4), int64(16), object(1)
memory usage: 224.3+ KB

In [153]:
df["Date"] = pd.to_datetime(df["Date"])

df["Month"] = df["Date"].dt.month
df["DayOfYear"] = df["Date"].dt.dayofyear
df["Year"] = df["Date"].dt.year

df.drop("Date", axis=1, inplace=True)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1305 entries, 0 to 1318
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   TempHighF                   1305 non-null   int64
 1   TempAvgF                    1305 non-null   int64
 2   TempLowF                    1305 non-null   int64
 3   DewPointHighF               1305 non-null   int64
 4   DewPointAvgF                1305 non-null   int64
 5   DewPointLowF                1305 non-null   int64
 6   HumidityHighPercent         1305 non-null   int64
 7   HumidityAvgPercent          1305 non-null   int64
 8   HumidityLowPercent          1305 non-null   int64
 9   SeaLevelPressureHighInches  1305 non-null   float64
 10  SeaLevelPressureAvgInches   1305 non-null   float64
 11  SeaLevelPressureLowInches   1305 non-null   float64
 12  VisibilityHighMiles         1305 non-null   int64
 13  VisibilityAvgMiles          1305 non-null   int64
 14  VisibilityLowMiles          1305 non-null   int64
 15  WindHighMPH                 1305 non-null   int64
 16  WindAvgMPH                  1305 non-null   int64
 17  WindGustMPH                 1305 non-null   int64
 18  PrecipitationSumInches      1305 non-null   float64
 19  Events                      1305 non-null   int64
 20  Month                       1305 non-null   int32
 21  DayOfYear                   1305 non-null   int32
 22  Year                        1305 non-null   int32
dtypes: float64(4), int32(3), int64(16)
memory usage: 229.4 KB

In [155]:
df.head()

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,...,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events,Month,DayOfYear,Year
0,74,60,45,67,49,43,93,75,57,43.0,...,7,2,20,4,31,0.46000,1,12,355,2013
1,56,48,39,43,36,28,93,68,43,28.0,...,10,5,16,6,25,0.00000,0,12,356,2013
2,58,45,32,31,27,23,76,52,27,23.0,...,10,10,8,3,12,0.00000,0,12,357,2013
3,61,46,31,36,28,21,89,56,22,21.0,...,10,7,12,4,20,0.00000,0,12,358,2013
4,58,50,41,44,40,36,86,71,56,36.0,...,10,7,10,2,16,0.12738,0,12,359,2013

In [156]:
df.isnull().sum()

TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
Month                         0
DayOfYear                     0
Year                          0
dtype: int64

In [157]:
X = df.drop('Events',axis=1)
y = df['Events']

In [159]:
y.value_counts()

Events
0    930
1    375
Name: count, dtype: int64

In [160]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42, stratify=y)

In [161]:
from sklearn.preprocessing import StandardScaler


ss = StandardScaler()
X_train_scale = ss.fit_transform(X_train)
X_test_scale = ss.transform(X_test)

In [163]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, recall_score, classification_report, f1_score

lr = LogisticRegression()
lr.fit(X_train_scale, y_train)
y_pred = lr.predict(X_test_scale)

y_pred_train = lr.predict(X_train_scale)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test----------')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.9042145593869731
0.8759398496240601
0.7766666666666666
0.823321554770318
[[711  33]
 [ 67 233]]
test----------
0.9195402298850575
0.921875
0.7866666666666666
0.8489208633093526
[[181   5]
 [ 16  59]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       186
           1       0.92      0.79      0.85        75

    accuracy                           0.92       261
   macro avg       0.92      0.88      0.90       261
weighted avg       0.92      0.92      0.92       261

In [164]:
from sklearn.svm import  SVC

svc = SVC()
svc.fit(X_train_scale, y_train)
y_pred = svc.predict(X_test_scale)

y_pred_train = svc.predict(X_train_scale)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test----------')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.9061302681992337
0.8976377952755905
0.76
0.8231046931407943
[[718  26]
 [ 72 228]]
test----------
0.8697318007662835
0.8360655737704918
0.68
0.75
[[176  10]
 [ 24  51]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91       186
           1       0.84      0.68      0.75        75

    accuracy                           0.87       261
   macro avg       0.86      0.81      0.83       261
weighted avg       0.87      0.87      0.87       261

In [167]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=101, max_depth=2)
rf.fit(X_train_scale, y_train)
y_pred = rf.predict(X_test_scale)

y_pred_train = rf.predict(X_train_scale)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test----------')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.935823754789272
0.9145907473309609
0.8566666666666667
0.8846815834767642
[[720  24]
 [ 43 257]]
test----------
0.9386973180076629
0.927536231884058
0.8533333333333334
0.8888888888888888
[[181   5]
 [ 11  64]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.96       186
           1       0.93      0.85      0.89        75

    accuracy                           0.94       261
   macro avg       0.94      0.91      0.92       261
weighted avg       0.94      0.94      0.94       261

In [168]:
from sklearn.naive_bayes import GaussianNB

naive = GaussianNB()
naive.fit(X_train_scale, y_train)
y_pred = naive.predict(X_test_scale)

y_pred_train = naive.predict(X_train_scale)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test----------')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.8697318007662835
0.7907801418439716
0.7433333333333333
0.7663230240549829
[[685  59]
 [ 77 223]]
test----------
0.8850574712643678
0.8169014084507042
0.7733333333333333
0.7945205479452054
[[173  13]
 [ 17  58]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       186
           1       0.82      0.77      0.79        75

    accuracy                           0.89       261
   macro avg       0.86      0.85      0.86       261
weighted avg       0.88      0.89      0.88       261