In [194]:
import pandas as pd

In [195]:
df =pd.read_csv('customer_feedback_sentiment.csv')

In [196]:
df.shape

(1000, 2)

In [197]:
df.head()

                            feedback_text  label
0        Very satisfied with my purchase.      1
1               Great experience overall.      1
2                  I'm very disappointed.      0
3    Fast delivery and perfect condition.      1
4  Terrible quality, not worth the price.      0

In [198]:
# df =df.drop_duplicates()

In [199]:
df.shape

(1000, 2)

In [200]:
df.isnull().sum()

feedback_text    0
label            0
dtype: int64

In [201]:
df.head()

                            feedback_text  label
0        Very satisfied with my purchase.      1
1               Great experience overall.      1
2                  I'm very disappointed.      0
3    Fast delivery and perfect condition.      1
4  Terrible quality, not worth the price.      0

In [202]:
import re

def clean_text(text):
    text = text.lower()

    #remove panchuation
    text = re.sub(r"[^a-z0-9]"," ",text)

    return text

df['feedback_text'] = df['feedback_text'].apply(clean_text)

In [203]:
df.head()

                            feedback_text  label
0        very satisfied with my purchase       1
1               great experience overall       1
2                  i m very disappointed       0
3    fast delivery and perfect condition       1
4  terrible quality  not worth the price       0

In [204]:
df.shape

(1000, 2)

In [205]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def remove_stop(text):
    tokens = word_tokenize(text)

    stop_words = stopwords.words('english')

    for word in tokens:
        if word in stop_words:
            text = text.replace(word,"")

    return text
df['feedback_text'] = df['feedback_text'].apply(remove_stop)

In [206]:
df.head()

                       feedback_text  label
0              satisfied   purchase       1
1          great experience overall       1
2                        dsapponted       0
3  fast delivery  perfect condition       1
4   terrible quality   worth  price       0

In [207]:
from nltk.stem import PorterStemmer

def stemming(text):

    ps = PorterStemmer()

    tokens = word_tokenize(text)

    stemmed_words = []

    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)


    return " ".join(stemmed_words)

df['feedback_text'] = df['feedback_text'].apply(stemming)

In [208]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
X = tf.fit_transform(df['feedback_text'])

In [209]:
df.head()

                  feedback_text  label
0               satisfi purchas      1
1           great experi overal      1
2                      dsappont      0
3  fast deliveri perfect condit      1
4   terribl qualiti worth price      0

In [210]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2875 stored elements and shape (1000, 30)>

In [211]:
y = df['label']

In [212]:
y.value_counts()

label
1    500
0    500
Name: count, dtype: int64

In [213]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [214]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix


lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_train = lr.predict(X_train)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

train
1.0
1.0
1.0
[[400   0]
 [  0 400]]
test
1.0
1.0
1.0
[[100   0]
 [  0 100]]

In [215]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [216]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train_scale = ss.fit_transform(X_train)
X_test_scale = ss.transform(X_test)

In [217]:
X_train_scale

array([[-0.32634444, -0.28730468, -0.30723158, ..., -0.30966177,
        -0.33564336, -0.30966177],
       [-0.32634444, -0.28730468, -0.30723158, ..., -0.30966177,
        -0.33564336, -0.30966177],
       [-0.32634444, -0.28730468, -0.30723158, ..., -0.30966177,
        -0.33564336,  3.22932987],
       ...,
       [-0.32634444, -0.28730468, -0.30723158, ..., -0.30966177,
         2.97935282, -0.30966177],
       [-0.32634444, -0.28730468, -0.30723158, ..., -0.30966177,
        -0.33564336, -0.30966177],
       [-0.32634444, -0.28730468,  3.25487371, ..., -0.30966177,
        -0.33564336, -0.30966177]], shape=(800, 30))

In [218]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix


rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred_train = rf.predict(X_train)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

train
1.0
1.0
1.0
[[400   0]
 [  0 400]]
test
1.0
1.0
1.0
[[100   0]
 [  0 100]]

In [219]:
from sklearn.naive_bayes import GaussianNB

naive = GaussianNB()
naive.fit(X_train, y_train)
y_pred = naive.predict(X_test)
y_pred_train = naive.predict(X_train)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

train
1.0
1.0
1.0
[[400   0]
 [  0 400]]
test
1.0
1.0
1.0
[[100   0]
 [  0 100]]

In [220]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


rf = RandomForestClassifier()
param = [{
    'n_estimators':[51,101],
    'max_depth':[2,3,4]
    
}]
grid = GridSearchCV(estimator=rf, param_grid=param, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)
y_pred_train = grid.predict(X_train)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

train
1.0
1.0
1.0
[[400   0]
 [  0 400]]
test
1.0
1.0
1.0
[[100   0]
 [  0 100]]

In [221]:
import joblib

joblib.dump(rf,'model.pkl')

['model.pkl']