In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.xls')

In [3]:
df.shape

(7043, 21)

In [4]:
df = df.drop_duplicates()

In [5]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df = df.drop('customerID',axis=1)

In [7]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [9]:
import numpy as np

df.replace(' ', np.nan, inplace=True)
df = df.dropna()

df['TotalCharges'] = df['TotalCharges'].astype(float)

In [10]:
df.shape

(7032, 20)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [12]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [13]:
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

ordinal_encode = OrdinalEncoder(dtype=np.int64)

df['Contract'] = ordinal_encode.fit_transform(df[['Contract']])

In [14]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,1,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes

In [15]:
df['Churn'] = df['Churn'].map({'Yes':1, 'No':0})

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   int64
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   int64
dtypes: float64(2), int64(4), object(14)
memory usage: 1.1+ MB

In [17]:
df['tenure'] = df['tenure'].astype(float)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   float64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   int64
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   int64
dtypes: float64(3), int64(3), object(14)
memory usage: 1.1+ MB

In [19]:
X = df.drop('Churn',axis=1)
y = df['Churn']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

num_cols = X.select_dtypes(include='float').columns
cat_cols = X.select_dtypes(include='object').columns


preproccesor = ColumnTransformer(transformers=[
    ('num', StandardScaler(), num_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])

In [22]:
X_train = preproccesor.fit_transform(X_train)
X_test = preproccesor.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, classification_report


lr = LogisticRegression(class_weight='balanced')
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
y_pred_train = lr.predict(X_train)
result = []

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print("*"*20)
print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'logistic',
    'train accuracy':accuracy_score(y_train, y_pred_train),
    'test accuracy': accuracy_score(y_test, y_pred),
    'train recall': recall_score(y_train, y_pred_train),
    'test recall' : recall_score(y_test, y_pred)
})

train
0.7586347013409184
0.7744648318042814
[[2721  893]
 [ 295 1013]]
              precision    recall  f1-score   support

           0       0.90      0.75      0.82      3614
           1       0.53      0.77      0.63      1308

    accuracy                           0.76      4922
   macro avg       0.72      0.76      0.73      4922
weighted avg       0.80      0.76      0.77      4922

********************
test
0.7369668246445498
0.7700534759358288
[[1123  426]
 [ 129  432]]
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1549
           1       0.50      0.77      0.61       561

    accuracy                           0.74      2110
   macro avg       0.70      0.75      0.71      2110
weighted avg       0.79      0.74      0.75      2110

In [31]:
from sklearn.naive_bayes import GaussianNB


naive = GaussianNB()
naive.fit(X_train, y_train)

y_pred = naive.predict(X_test)
y_pred_train = naive.predict(X_train)


print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print("*"*20)
print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'naive',
    'train accuracy':accuracy_score(y_train, y_pred_train),
    'test accuracy': accuracy_score(y_test, y_pred),
    'train recall': recall_score(y_train, y_pred_train),
    'test recall' : recall_score(y_test, y_pred)
})

train
0.6540024380333198
0.8746177370030581
[[2075 1539]
 [ 164 1144]]
              precision    recall  f1-score   support

           0       0.93      0.57      0.71      3614
           1       0.43      0.87      0.57      1308

    accuracy                           0.65      4922
   macro avg       0.68      0.72      0.64      4922
weighted avg       0.79      0.65      0.67      4922

********************
test
0.6417061611374407
0.8556149732620321
[[874 675]
 [ 81 480]]
              precision    recall  f1-score   support

           0       0.92      0.56      0.70      1549
           1       0.42      0.86      0.56       561

    accuracy                           0.64      2110
   macro avg       0.67      0.71      0.63      2110
weighted avg       0.78      0.64      0.66      2110

In [33]:
from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
y_pred_train = knn.predict(X_train)


print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print("*"*20)
print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'knn',
    'train accuracy':accuracy_score(y_train, y_pred_train),
    'test accuracy': accuracy_score(y_test, y_pred),
    'train recall': recall_score(y_train, y_pred_train),
    'test recall' : recall_score(y_test, y_pred)
})

train
0.8646891507517269
0.6987767584097859
[[3342  272]
 [ 394  914]]
              precision    recall  f1-score   support

           0       0.89      0.92      0.91      3614
           1       0.77      0.70      0.73      1308

    accuracy                           0.86      4922
   macro avg       0.83      0.81      0.82      4922
weighted avg       0.86      0.86      0.86      4922

********************
test
0.747867298578199
0.5294117647058824
[[1281  268]
 [ 264  297]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83      1549
           1       0.53      0.53      0.53       561

    accuracy                           0.75      2110
   macro avg       0.68      0.68      0.68      2110
weighted avg       0.75      0.75      0.75      2110

In [34]:
from sklearn.svm import SVC


svc = SVC(class_weight='balanced')
svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)


print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print("*"*20)
print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'svc',
    'train accuracy':accuracy_score(y_train, y_pred_train),
    'test accuracy': accuracy_score(y_test, y_pred),
    'train recall': recall_score(y_train, y_pred_train),
    'test recall' : recall_score(y_test, y_pred)
})

train
0.7732629012596506
0.8295107033639144
[[2721  893]
 [ 223 1085]]
              precision    recall  f1-score   support

           0       0.92      0.75      0.83      3614
           1       0.55      0.83      0.66      1308

    accuracy                           0.77      4922
   macro avg       0.74      0.79      0.75      4922
weighted avg       0.82      0.77      0.78      4922

********************
test
0.7355450236966825
0.7807486631016043
[[1114  435]
 [ 123  438]]
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1549
           1       0.50      0.78      0.61       561

    accuracy                           0.74      2110
   macro avg       0.70      0.75      0.71      2110
weighted avg       0.79      0.74      0.75      2110

In [35]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=101, max_depth=3,class_weight='balanced')
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred_train = rf.predict(X_train)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print("*"*20)
print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'random forest',
    'train accuracy':accuracy_score(y_train, y_pred_train),
    'test accuracy': accuracy_score(y_test, y_pred),
    'train recall': recall_score(y_train, y_pred_train),
    'test recall' : recall_score(y_test, y_pred)
})

train
0.7401462819991873
0.8019877675840978
[[2594 1020]
 [ 259 1049]]
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      3614
           1       0.51      0.80      0.62      1308

    accuracy                           0.74      4922
   macro avg       0.71      0.76      0.71      4922
weighted avg       0.80      0.74      0.75      4922

********************
test
0.7132701421800948
0.7825311942959001
[[1066  483]
 [ 122  439]]
              precision    recall  f1-score   support

           0       0.90      0.69      0.78      1549
           1       0.48      0.78      0.59       561

    accuracy                           0.71      2110
   macro avg       0.69      0.74      0.69      2110
weighted avg       0.79      0.71      0.73      2110

In [36]:
results = pd.DataFrame(result)
results

           model  train accuracy  test accuracy  train recall  test recall
0       logistic        0.758635       0.736967      0.774465     0.770053
1          naive        0.654002       0.641706      0.874618     0.855615
2            knn        0.864689       0.747867      0.698777     0.529412
3            svc        0.773263       0.735545      0.829511     0.780749
4  random forest        0.740146       0.713270      0.801988     0.782531