In [118]:
import pandas as pd

In [119]:
df =pd.read_csv('employee_attrition_dataset.csv')

In [120]:
df.head()

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Female,Married,IT,Manager,1,15488,28,15,...,No,6,54,17,4,4,4,20,3,No
1,2,48,Female,Married,Sales,Assistant,5,13079,28,6,...,Yes,2,45,1,4,1,2,25,2,No
2,3,34,Male,Married,Marketing,Assistant,1,13744,24,24,...,Yes,6,34,2,3,4,4,45,3,No
3,4,27,Female,Divorced,Marketing,Manager,1,6809,26,10,...,No,9,48,18,2,3,1,35,3,No
4,5,40,Male,Divorced,Marketing,Executive,1,10206,52,29,...,No,3,33,0,4,1,3,44,3,No

In [121]:
df.shape

(1000, 26)

In [122]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

In [123]:
df = df.drop_duplicates()

In [124]:
df = df.drop('Employee_ID',axis=1)

In [125]:
df.describe()

,Age,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,Years_Since_Last_Promotion,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Training_Hours_Last_Year,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,39.991000,3.055000,11499.899000,57.837000,14.922000,7.539000,4.40800,2.495000,3.151000,2.52700,50.043000,4.877000,44.553000,9.524000,2.494000,2.519000,2.503000,24.507000,2.484000
std,11.780055,1.399977,4920.529231,24.702037,8.350548,4.001061,2.99508,1.105077,1.426967,1.13073,28.204657,2.546833,8.704192,5.973534,1.110494,1.106736,1.099636,14.138099,1.111296
min,20.000000,1.000000,3001.000000,15.000000,1.000000,1.000000,0.00000,1.000000,1.000000,1.00000,0.000000,1.000000,30.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,30.000000,2.000000,7395.750000,36.000000,8.000000,4.000000,2.00000,2.000000,2.000000,2.00000,26.000000,3.000000,37.000000,4.000000,2.000000,2.000000,2.000000,12.000000,1.000000
50%,41.000000,3.000000,11256.000000,58.000000,15.000000,8.000000,4.00000,3.000000,3.000000,3.00000,50.000000,5.000000,45.000000,9.000000,2.000000,3.000000,3.000000,24.000000,2.000000
75%,50.250000,4.000000,15855.000000,80.000000,22.000000,11.000000,7.00000,3.000000,4.000000,4.00000,75.250000,7.000000,52.000000,15.000000,4.000000,4.000000,3.000000,37.000000,3.000000
max,59.000000,5.000000,19999.000000,99.000000,29.000000,14.000000,9.00000,4.000000,5.000000,4.00000,99.000000,9.000000,59.000000,19.000000,4.000000,4.000000,4.000000,49.000000,4.000000

In [126]:
df.head()

,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,58,Female,Married,IT,Manager,1,15488,28,15,4,...,No,6,54,17,4,4,4,20,3,No
1,48,Female,Married,Sales,Assistant,5,13079,28,6,9,...,Yes,2,45,1,4,1,2,25,2,No
2,34,Male,Married,Marketing,Assistant,1,13744,24,24,14,...,Yes,6,34,2,3,4,4,45,3,No
3,27,Female,Divorced,Marketing,Manager,1,6809,26,10,8,...,No,9,48,18,2,3,1,35,3,No
4,40,Male,Divorced,Marketing,Executive,1,10206,52,29,10,...,No,3,33,0,4,1,3,44,3,No

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            1000 non-null   int64
 1   Gender                         1000 non-null   object
 2   Marital_Status                 1000 non-null   object
 3   Department                     1000 non-null   object
 4   Job_Role                       1000 non-null   object
 5   Job_Level                      1000 non-null   int64
 6   Monthly_Income                 1000 non-null   int64
 7   Hourly_Rate                    1000 non-null   int64
 8   Years_at_Company               1000 non-null   int64
 9   Years_in_Current_Role          1000 non-null   int64
 10  Years_Since_Last_Promotion     1000 non-null   int64
 11  Work_Life_Balance              1000 non-null   int64
 12  Job_Satisfaction               1000 non-null   int64
 13  Performance_Rating             1000 non-null   int64
 14  Training_Hours_Last_Year       1000 non-null   int64
 15  Overtime                       1000 non-null   object
 16  Project_Count                  1000 non-null   int64
 17  Average_Hours_Worked_Per_Week  1000 non-null   int64
 18  Absenteeism                    1000 non-null   int64
 19  Work_Environment_Satisfaction  1000 non-null   int64
 20  Relationship_with_Manager      1000 non-null   int64
 21  Job_Involvement                1000 non-null   int64
 22  Distance_From_Home             1000 non-null   int64
 23  Number_of_Companies_Worked     1000 non-null   int64
 24  Attrition                      1000 non-null   object
dtypes: int64(19), object(6)
memory usage: 195.4+ KB

In [128]:
df['Overtime'] = df['Overtime'].map({'Yes':1, 'No':0})
df['Attrition'] = df['Attrition'].map({'Yes':1, 'No':0})

In [129]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']

In [130]:
y.value_counts()

Attrition
0    811
1    189
Name: count, dtype: int64

In [131]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [132]:
df.iloc[:,20:]

,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,4,4,20,3,0
1,1,2,25,2,0
2,4,4,45,3,0
3,3,1,35,3,0
4,1,3,44,3,0
...,...,...,...,...,...
995,1,4,24,4,0
996,2,4,39,3,1
997,3,3,33,2,0
998,1,4,41,4,0
999,4,3,43,2,0

In [133]:
X_train.shape

(800, 24)

In [134]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

scale_col = ['Age','Monthly_Income','Hourly_Rate','Years_at_Company','Years_in_Current_Role','Training_Hours_Last_Year','Average_Hours_Worked_Per_Week','Absenteeism','Distance_From_Home']
encode_col = ['Gender', 'Marital_Status', 'Department', 'Job_Role']

preprocessor = ColumnTransformer(transformers=[('ss', StandardScaler(), scale_col),
                                               ('cat', OneHotEncoder(handle_unknown='ignore',sparse_output=False, drop='first'), encode_col),
                                        
],remainder='passthrough')

In [135]:
X_train_preproced = preprocessor.fit_transform(X_train)
X_test_preproced = preprocessor.transform(X_test)

In [136]:
X_train_preproced.shape

(800, 30)

In [137]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_preproced, y_train)

In [138]:
y_train_smote.value_counts()

Attrition
0    649
1    649
Name: count, dtype: int64

In [139]:
# from imblearn.pipeline import Pipeline
# from imblearn.over_sampling import SMOTE
# from sklearn.linear_model import LogisticRegression

# pipeline = Pipeline([
#     ('Preprocess', preprocessor),
#     ('Smote', SMOTE(random_state=42)),
#     ('model', LogisticRegression())
# ])

In [143]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report, f1_score, recall_score
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train_smote, y_train_smote)
y_pred = lr.predict(X_test_preproced)
y_pred_train = lr.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result =[]
result.append({
    'model':'logitic',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.6040061633281972
0.6030534351145038
0.6086286594761171
0.6058282208588958
[[389 260]
 [254 395]]
              precision    recall  f1-score   support

           0       0.60      0.60      0.60       649
           1       0.60      0.61      0.61       649

    accuracy                           0.60      1298
   macro avg       0.60      0.60      0.60      1298
weighted avg       0.60      0.60      0.60      1298

-------test ----
0.52
0.16279069767441862
0.3684210526315789
0.22580645161290322
[[90 72]
 [24 14]]
              precision    recall  f1-score   support

           0       0.79      0.56      0.65       162
           1       0.16      0.37      0.23        38

    accuracy                           0.52       200
   macro avg       0.48      0.46      0.44       200
weighted avg       0.67      0.52      0.57       200

In [144]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_smote, y_train_smote)
y_pred = knn.predict(X_test_preproced)
y_pred_train = knn.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'knn',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.8197226502311248
0.7360637087599545
0.9969183359013868
0.8468586387434555
[[417 232]
 [  2 647]]
              precision    recall  f1-score   support

           0       1.00      0.64      0.78       649
           1       0.74      1.00      0.85       649

    accuracy                           0.82      1298
   macro avg       0.87      0.82      0.81      1298
weighted avg       0.87      0.82      0.81      1298

-------test ----
0.44
0.17543859649122806
0.5263157894736842
0.2631578947368421
[[68 94]
 [18 20]]
              precision    recall  f1-score   support

           0       0.79      0.42      0.55       162
           1       0.18      0.53      0.26        38

    accuracy                           0.44       200
   macro avg       0.48      0.47      0.41       200
weighted avg       0.67      0.44      0.49       200

In [145]:
from sklearn.naive_bayes import GaussianNB

naive = GaussianNB()
naive.fit(X_train_smote, y_train_smote)
y_pred = naive.predict(X_test_preproced)
y_pred_train = naive.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


result.append({
    'model':'naive',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.7434514637904468
0.7507936507936508
0.7288135593220338
0.7396403440187647
[[492 157]
 [176 473]]
              precision    recall  f1-score   support

           0       0.74      0.76      0.75       649
           1       0.75      0.73      0.74       649

    accuracy                           0.74      1298
   macro avg       0.74      0.74      0.74      1298
weighted avg       0.74      0.74      0.74      1298

-------test ----
0.615
0.1320754716981132
0.18421052631578946
0.15384615384615385
[[116  46]
 [ 31   7]]
              precision    recall  f1-score   support

           0       0.79      0.72      0.75       162
           1       0.13      0.18      0.15        38

    accuracy                           0.61       200
   macro avg       0.46      0.45      0.45       200
weighted avg       0.66      0.61      0.64       200

In [146]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train_smote, y_train_smote)
y_pred = svc.predict(X_test_preproced)
y_pred_train = svc.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'svc',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.827426810477658
0.7860026917900403
0.8998459167950693
0.8390804597701149
[[490 159]
 [ 65 584]]
              precision    recall  f1-score   support

           0       0.88      0.76      0.81       649
           1       0.79      0.90      0.84       649

    accuracy                           0.83      1298
   macro avg       0.83      0.83      0.83      1298
weighted avg       0.83      0.83      0.83      1298

-------test ----
0.59
0.14516129032258066
0.23684210526315788
0.18
[[109  53]
 [ 29   9]]
              precision    recall  f1-score   support

           0       0.79      0.67      0.73       162
           1       0.15      0.24      0.18        38

    accuracy                           0.59       200
   macro avg       0.47      0.45      0.45       200
weighted avg       0.67      0.59      0.62       200

In [147]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier()
param =[{
    'n_estimators':[101,201,301],
    'max_depth':[2,3,4]
}]
grid = GridSearchCV(estimator=rf, param_grid=param, cv=5, n_jobs=3)
grid.fit(X_train_smote, y_train_smote)
y_pred = grid.predict(X_test_preproced)
y_pred_train = grid.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'random forest cv',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.8913713405238829
0.9535714285714286
0.8228043143297381
0.8833746898263027
[[623  26]
 [115 534]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.90       649
           1       0.95      0.82      0.88       649

    accuracy                           0.89      1298
   macro avg       0.90      0.89      0.89      1298
weighted avg       0.90      0.89      0.89      1298

-------test ----
0.78
0.25
0.07894736842105263
0.12
[[153   9]
 [ 35   3]]
              precision    recall  f1-score   support

           0       0.81      0.94      0.87       162
           1       0.25      0.08      0.12        38

    accuracy                           0.78       200
   macro avg       0.53      0.51      0.50       200
weighted avg       0.71      0.78      0.73       200

In [148]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=101, max_depth=2)
rf.fit(X_train_smote, y_train_smote)
y_pred = rf.predict(X_test_preproced)
y_pred_train = rf.predict(X_train_smote)

print('train')
print(accuracy_score(y_train_smote, y_pred_train))
print(precision_score(y_train_smote, y_pred_train))
print(recall_score(y_train_smote, y_pred_train))
print(f1_score(y_train_smote, y_pred_train))
print(confusion_matrix(y_train_smote, y_pred_train))
print(classification_report(y_train_smote, y_pred_train))

print("-------test ----")
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

result.append({
    'model':'random forest',
    'train accuracy':accuracy_score(y_train_smote, y_pred_train),
    'test accuracy':accuracy_score(y_test, y_pred),
    'train precision': precision_score(y_train_smote, y_pred_train),
    'test precision': precision_score(y_test, y_pred),
    'train recall': recall_score(y_train_smote, y_pred_train),
    'test recall': recall_score(y_test, y_pred),
    'train f1 ':f1_score(y_train_smote, y_pred_train),
    'test f1': f1_score(y_test, y_pred),
})

train
0.7896764252696457
0.7848484848484848
0.7981510015408321
0.7914438502673797
[[507 142]
 [131 518]]
              precision    recall  f1-score   support

           0       0.79      0.78      0.79       649
           1       0.78      0.80      0.79       649

    accuracy                           0.79      1298
   macro avg       0.79      0.79      0.79      1298
weighted avg       0.79      0.79      0.79      1298

-------test ----
0.65
0.2037037037037037
0.2894736842105263
0.2391304347826087
[[119  43]
 [ 27  11]]
              precision    recall  f1-score   support

           0       0.82      0.73      0.77       162
           1       0.20      0.29      0.24        38

    accuracy                           0.65       200
   macro avg       0.51      0.51      0.51       200
weighted avg       0.70      0.65      0.67       200

In [149]:
results = pd.DataFrame(result)
results

,model,train accuracy,test accuracy,train precision,test precision,train recall,test recall,train f1,test f1
0,logitic,0.604006,0.520,0.603053,0.162791,0.608629,0.368421,0.605828,0.225806
1,knn,0.819723,0.440,0.736064,0.175439,0.996918,0.526316,0.846859,0.263158
2,naive,0.743451,0.615,0.750794,0.132075,0.728814,0.184211,0.739640,0.153846
3,svc,0.827427,0.590,0.786003,0.145161,0.899846,0.236842,0.839080,0.180000
4,random forest cv,0.891371,0.780,0.953571,0.250000,0.822804,0.078947,0.883375,0.120000
5,random forest,0.789676,0.650,0.784848,0.203704,0.798151,0.289474,0.791444,0.239130